export default {
  items: null,
  search: null,
  current: null,
  data: null,
  studentProgress: null,
  studentProgressDetails: null,
  modalReadMoreAnnouncement: false,
  announcementToRead: null,
  offerings: [],
  competencyList: [],
  classroomSetStatusFinal: false,
  studentsCompetencyList: [],
  notifications: [],
  enrollmentExaminations: [],
  onTutorial: false,
  preProjectList: [],
  projectList: [],
  preProjectGroups: [],
  historyActionpreProject: [],
  facialRecognition: {
    active: false,
    token: null,
    next: null,
    activeTool: false,
  },
  floatingNotes: {
    active: false,
    data: {},
    note_id: null,
  },
  preProjectGroupList: [],
  preProjectStudentList: [],
  categoryListKb: [],
  preProjetcGroupSessionList: [],
  externalLink: [],
}
