on:
  push:
    branches:
      - homolog

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sonar Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}

  Build-homolog:
    if: ${{ github.ref_name == 'homolog'}}
    runs-on: ubuntu-latest
    container:
      image: curlimages/curl:latest
    steps:
      - name: Check Time and Schedule
        run: |
              echo "Running immediately on homolog branch."
              echo "Iniciando pipe"
              curl -u "dot-devops-service-admin-edit-view:1105e35010808275578bd1c28124e61aad" -k -X POST "https://jenkins-hom-jenkins-okd4.apps.okd-hom.dotgroup.com.br/job/studion-spa/build?token=TokenStudionSpa"
        
  #Build-producao:
  #  if: ${{ github.ref_name == 'master'}}
  #  runs-on: ubuntu-latest
  #  container:
  #    image: curlimages/curl:latest
  #  # container:
  #    # image: curlimages/curl:latest
  #  steps:
  #    - name: Check Time and Schedule
  #      run: |
  #        CURRENT_HOUR=$(TZ=America/Sao_Paulo date +"%H")
  #        if [ "$GITHUB_REF" == "master" ]; then
  #          if [ "$CURRENT_HOUR" -ge 19 ] || [ "$CURRENT_HOUR" -lt 8 ]; then
  #            echo "Current time is between 19:00 and 08:00 UTC, running immediately."
  #            echo "Iniciando pipe"
  #            echo "20 22 * * * curl -X POST https://api.github.com/repos/<username>/<repo>/actions/workflows/secondary-workflow.yml/dispatches \
  #                 -H 'Accept: application/vnd.github.v3+json' \
  #                 -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
  #                 -d '{\"ref\":\"master\"}'" | crontab -
  #          else
  #            echo "Current time is outside 19:00 and 08:00 UTC, scheduling workflow."
  #            gh workflow run master.yml
  #          fi
  #        fi
