import config from '@/config'
const { CUSTOM_PASSWORD_REQUIREMENTS } = config

export const DEFAULT_MIN_PASSWORD_SIZE = 8
export const DEFAULT_MAX_PASSWORD_SIZE = 50
let MIN_PASSWORD_SIZE = DEFAULT_MIN_PASSWORD_SIZE

if (CUSTOM_PASSWORD_REQUIREMENTS && CUSTOM_PASSWORD_REQUIREMENTS.ENABLED && CUSTOM_PASSWORD_REQUIREMENTS.SIZE) {
  MIN_PASSWORD_SIZE = CUSTOM_PASSWORD_REQUIREMENTS.SIZE
}
export default MIN_PASSWORD_SIZE
