const NAMESPACE = 'Mediation'

export const SET_ACTIONS = `${NAMESPACE}/SET_ACTIONS`
export const SET_MEDIATION_LIST = `${NAMESPACE}/SET_MEDIATION_LIST`
export const SET_MEDIATION_AVAILABLE_LINKS = `${NAMESPACE}/SET_MEDIATION_AVAILABLE_LINKS`
export const ADD_MEDIATION_LINKS = `${NAMESPACE}/ADD_MEDIATION_LINKS`
export const REMOVE_MEDIATION_LINK = `${NAMESPACE}/REMOVE_MEDIATION_LINK`
export const SET_MEDIATION_PLAN = `${NAMESPACE}/SET_MEDIATION_PLAN`
export const SET_MEDIATION_LINKS = `${NAMESPACE}/SET_MEDIATION_LINKS`
export const SET_MEDIATION_FILTERS = `${NAMESPACE}/SET_MEDIATION_FILTERS`
export const SET_MEDIATION_TAGS = `${NAMESPACE}/SET_MEDIATION_TAGS`
export const SET_MEDIATION_TEMPLATES = `${NAMESPACE}/SET_MEDIATION_TEMPLATES`
export const SET_MEDIATION_BATCHES_LIST = `${NAMESPACE}/SET_MEDIATION_BATCHES_LIST`
export const SET_CUSTOM_INSTRUCTIONS = `${NAMESPACE}/SET_CUSTOM_INSTRUCTIONS`
export const ADD_CUSTOM_PM_TAG = `${NAMESPACE}/ADD_CUSTOM_PM_TAG`
export const SET_SCHEDULED_LIST_RESOURCE = `${NAMESPACE}/SET_SCHEDULED_LIST_RESOURCE`
