const NAMESPACE = 'account'
export const SET_FEATURED_CONTENTS_LIST = `${NAMESPACE}/SET_FEATURED_CONTENTS_LIST`
export let SET_FEATURED_CONTENTS_ITEM = `${NAMESPACE}/SET_FEATURED_CONTENTS_ITEM`
export const MOVE_FEATURED_CONTENT = 'featuredContents/MOVE_FEATURED_CONTENT'
export const DELETE_FEATURED_CONTENT = 'featuredContents/DELETE_FEATURED_CONTENT'
