const NAMESPACE = 'filters'

export const SET_FILTERS = `${NAMESPACE}/SET_FILTERS`
export const SET_FILTER_PREVIEW_DATA = `${NAMESPACE}/SET_FILTER_PREVIEW_DATA`
export const SET_FILTER_TYPES = `${NAMESPACE}/SET_FILTER_TYPES`
export const SET_CACHE_CONTENT_STATUS = `${NAMESPACE}/SET_CACHE_CONTENT_STATUS`
