const NAMESPACE = 'Evaluations'

export const SET_EVALUATIONS_LIST_RESOURCE = `${NAMESPACE}/SET_EVALUATIONS_LIST_RESOURCE`
export const SET_PRE_PROJECT_LIST_RESOURCE = `${NAMESPACE}/SET_PRE_PROJECT_LIST_RESOURCE`